config/routes.rb
AnatolyEdouard::Application.routes.draw do
  root  "greeting#index"
  devise_for :users

end

app/models/course.rb
class Course < ActiveRecord::Base
belongs_to :author, :class_name => 'User'
has_many :course_relationships, foreign_key: "followed_course_id", dependent: :destroy
has_many :students, through: :course_relationships, source: :student

end

app/models/course_relationship.rb
class CourseRelationship < ActiveRecord::Base
belongs_to :student, class_name: "User"
belongs_to :followed_course, class_name: "Course"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation     
has_many :authored_courses, class_name: 'Course', foreign_key: 'author_id', dependent: :destroy

has_many :course_relationships, foreign_key: "follower_id", dependent: :destroy
has_many :followed_courses, through: :course_relationships, source: :followed_course

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/greeting_controller.rb
class GreetingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greeting_helper.rb
module GreetingHelper
end

app/views/greeting/index.html.erb
<h1>Greeting#index</h1>
<p>Find me in app/views/greeting/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnatolyEdouard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<p class="navbar-text pull-right">
	
	<div id="page">
		<div id="primary-nav" class="hide-if-iframed">
			<a class="logo" href="/"><span>Lucidchart</span></a>
			<div id="user_nav" class = "user-info">
				<% if user_signed_in? %>
				  <div id = "login-user" class="tab">Hi. <strong><%= current_user.email %></strong>!</div>
				  <div class="tab">
				  	<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
				  	<div class="arrow-r-13"></div>
				  </div>
				  <div class="tab">
				  	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link '  %><div class="arrow-r-13"></div>
				  </div>
				<% else %>
				 <div class="tab">
				  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> <div class="arrow-r-13"></div>
				 </div>
				 <div class="tab">
				  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				  <div class="arrow-r-13"></div>
				 </div>
				<% end %>

			</div>	
		</div>
		<div id="page-body">
			<div id="page-content" class="container_12">
			   <div id="content" class="grid_12 lucid">
			   	   <%= yield %>
			   </div>
			</div>
			<div class="clear"></div>
		</div>
    </div>

</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Already signed up? Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "New to Lucidchart? Sign up free", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>